version: '3'

services:
  revibe:
    image: ghcr.io/kaiquenog/revibe:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.revibe.rule=Host(`institutorevibe.com.br`)"
      - "traefik.http.services.revibe.loadbalancer.server.port=80"
      - "traefik.http.routers.revibe.entrypoints=websecure"
      - "traefik.http.routers.revibe.tls=true"
    networks:
      - network_swarm_public

networks:
  network_swarm_public:
    external: true 