version: '3.8'

services:
  revibe:
    build:
      context: .
      dockerfile: dockerizer/Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.revibe.rule=Host(`institutorevibe.com.br`)"  # Substitua pelo seu domínio
      - "traefik.http.routers.revibe.entrypoints=websecure"
      - "traefik.http.routers.revibe.tls=true"
      - "traefik.http.services.revibe.loadbalancer.server.port=80"
    networks:
      - traefik-public
    restart: unless-stopped

networks:
  traefik-public:
    external: true 