version: '3.8'

services:
  revibe:
    image: ghcr.io/kaiquenog/instrevibe:main
    hostname: "{{.Service.Name}}.{{.Task.Slot}}"
    deploy:
      placement:
        constraints:
          - node.platform.arch == x86_64
      replicas: 1
      restart_policy:
        condition: on-failure
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.revibe.rule=Host(`institutorevibe.com.br`)"  # Substitua pelo seu domínio
      - "traefik.http.routers.revibe.entrypoints=websecure"
      - "traefik.http.routers.revibe.tls=true"
      - "traefik.http.services.revibe.loadbalancer.server.port=80"
    networks:
      - network_swarm_public

networks:
  network_swarm_public:
    external: true 